export const nameFixes = {
  category: {
    "ber-Nenm": "Uber-Nenééém",
    "culos Escuros": "Óculos Escuros",
    "gua Sanitria": "Água Sanitária",
    "gua de Coco": "Água de Coco",
    "gua": "Água",
    "lcool": "Álcool",
    "leo": "Óleo",
    "nibus": "Ônibus",
    "Acar": "Açúcar",
    "Aa": "Açaí",
    "ANUIDADE CARTO": "ANUIDADE CARTÃO",
    "Adaptador sada dupla para fone.": "Adaptador saída dupla para fone.",
    "Adoante": "Adoçante",
    "Alfinete de segurana": "Alfinete de segurança",
    "Algodo": "Algodão",
    "Alho por": "Alho poró",
    "Almoo": "Almoço",
    "Aniversariantes do ms": "Aniversariantes do mês",
    "Antiinflamatrio": "Antiinflamatório",
    "Aparelho Eletrnico": "Aparelho Eletrônico",
    "Aspirador de p": "Aspirador de pó",
    "Assistncia Tcnica": "Assisténcia Técnica",
    "Avio": "Avião",
    "Balana": "Balança",
    "Bar": "Baré",
    "Benefcio": "Benefício",
    "Bloco Higinico": "Bloco Higiênico",
    "Bomba de gua": "Bomba de água",
    "Cpia Autenticada": "Cópia Autenticada",
    "Cpias": "Cópias",
    "CARTO BB TOTAL": "CARTÃO BB TOTAL",
    "Cabo eltrico": "Cabo elétrico",
    "Cachaa": "Cachaça",
    "Caf com Arte": "Café com Arte",
    "Caf da Manh": "Café da Manhã",
    "Caf em p": "Café em pó",
    "Caf": "Café",
    "Caixa de Fsforos": "Caixa de Fósforos",
    "Camaro": "Camarão",
    "Capa para colcho": "Capa para colchão",
    "Capa para garrafo": "Capa para garrafão",
    "Carto de Crdito": "Cartão de Crédito",
    "Cartrio": "Cartório",
    "Carvo": "Carvão",
    "Cerveja Sem lcool": "Cerveja Sem álcool",
    "Ch": "Chá",
    "Cigarro Eletrnico": "Cigarro Eletrônico",
    "Colrio": "Colírio",
    "Combustvel": "Combustível",
    "Condomnio Algarve 1108": "Condomínio Algarve 1108",
    "Condomnio JP 702": "Condomínio JP 702",
    "Consulta Mdica": "Consulta Médica",
    "Contribuio PF": "Contribuição PF",
    "Contribuio PJ": "Contribuição PJ",
    "Cordas de Violo": "Cordas de Violão",
    "Crdito": "Crédito",
    "Depsito": "Depósito",
    "Depilao": "Depilação",
    "Dersani Genrico": "Dersani Genérico",
    "Descartveis": "Descartáveis",
    "Desinsetizao": "Desinsetização",
    "Doao Extraoficial": "Doação Extraoficial",
    "Doao Oficial": "Doação Oficial",
    "Ducha higinica": "Ducha higiênica",
    "Elptico": "Elíptico",
    "Eletrodomstico": "Eletrodoméstico",
    "Escorredor de loua": "Escorredor de louça",
    "Escova de mo": "Escova de mão",
    "Escova sanitria": "Escova sanitária",
    "Esfrego": "Esfregão",
    "Espanadeira e p": "Espanadeira e pá",
    "Essncia": "Essência",
    "Estorno de crdito": "Estorno de crédito",
    "Estorno de dbito": "Estorno de débito",
    "Extenso Eltrica": "Extensão Elétrica",
    "Extenso eltrica": "Extensão elétrica",
    "Fabrcio": "Fabrício",
    "Farinha lctea": "Farinha láctea",
    "Feijo": "Feijão",
    "Filme plstico": "Filme plástico",
    "Fogo": "Fogão",
    "Garom": "Garçom",
    "Garrafo de gua de 20l": "Garrafão de água de 20l",
    "Gin Tnica": "Gin Tônica",
    "Guaran 600ml": "Guaraná 600ml",
    "Guaran Zero 1": "Guaraná Zero 1",
    "Guaran Zero 2l": "Guaraná Zero 2l",
    "Guaran Zero 600ml": "Guaraná Zero 600ml",
    "Guaran": "Guaraná",
    "Guia Turstico": "Guia Turístico",
    "Hlice de ventilador": "Hélice de ventilador",
    "Hortel": "Hortelã",
    "Im": "Imã",
    "Impresso": "Impressão",
    "Incensrio": "Incensário",
    "Inscrio": "Inscrição",
    "Instalao de fogo": "Instalação de fogão",
    "Jia": "Jóia",
    "Lmina de barbear": "Lâmina de barbear",
    "Lmpada": "Lâmpada",
    "Lpis de cor": "Lápis de cor",
    "Lquido": "Líquido",
    "Leite em P": "Leite em Pó",
    "Lenol": "Lençol",
    "Lenos Umedecidos": "Lenços Umedecidos",
    "Limo": "Limão",
    "Lingia": "Linguica",
    "Lustra mveis": "Lustra móveis",
    "Luva Mgica": "Luva Mágica",
    "Luvas Cirrgicas": "Luvas Cirúrgicas",
    "Me": "Mãe",
    "Mgico": "Mágico",
    "Mquina de Cortar Cabelo": "Máquina de Cortar Cabelo",
    "Mquina de remar": "Máquina de remar",
    "Mscara": "Máscara",
    "Ma": "Maçã",
    "Macarro": "Macarrão",
    "Mamo": "Mamão",
    "Mecnico": "Mecânico",
    "Melo": "Melão",
    "Mormao": "Mormaço",
    "Moto-Txi": "Moto-Táxi",
    "Mudana": "Mudança",
    "No identificado": "Não identificado",
    "No registrado?": "Não registrado?",
    "Nescau Light em p": "Nescau Light em pó",
    "Nova Itlia Danceteria": "Nova Itália Danceteria",
    "Organo": "Orégano",
    "P": "Pá",
    "Po de Queijo": "Pão de Queijo",
    "Po de alho": "Pão de alho",
    "Po": "Pão",
    "Ps de cama": "Pés de cama",
    "Palha de ao": "Palha de aço",
    "Pano de cho": "Pano de chão",
    "Papel Alumnio": "Papel Alumínio",
    "Papel Higinico": "Papel Higiênico",
    "Paracetamol + fosfato de codena": "Paracetamol + fosfato de codeína",
    "Pat": "Patê",
    "Pea": "Peça",
    "Peas": "Peças",
    "Picol": "Picolé",
    "Pina": "Pinça",
    "Placa lgica para HD": "Placa lógica para HD",
    "Plano de sade": "Plano de saúde",
    "Podlogo": "Podólogo",
    "Porta esponja e lava-louas": "Porta esponja e lava-louças",
    "Porta loua secando": "Porta louça secando",
    "Prato Vero": "Prato Verão",
    "Rao": "Ração",
    "Rede de proteo": "Rede de proteção",
    "Remdio": "Remédio",
    "Requeijo": "Requeijão",
    "Resciso": "Rescisão",
    "Resistncia": "Resistência",
    "Sabo": "Sabão",
    "Sabonete Lquido": "Sabonete Líquido",
    "Sandlias": "Sandálias",
    "Sanduche": "Sanduíche",
    "Saponceo": "Saponáceo",
    "Seguro Carto": "Seguro Cartão",
    "Seguro Fiana": "Seguro Fiança",
    "Seguro Incndio": "Seguro Incêndio",
    "Shake de Protena": "Shake de Proteína",
    "Sof": "Sofá",
    "Soro fisiolgico": "Soro fisiológico",
    "Suporte para violo": "Suporte para violão",
    "Tbua de corte": "Tábua de corte",
    "Tnis": "Ténis",
    "Txi": "Táxi",
    "TRANSFERNCIA": "TRANSFERÊNCIA",
    "Tacac": "Tacacá",
    "Tapete higinico": "Tapete higiênico",
    "Tarracha para violo": "Tarracha para violão",
    "Taxa nica": "Taxa única",
    "Tela Plstica": "Tela Plástica",
    "Tela metlica": "Tela metálica",
    "Televiso": "Televisão",
    "Templrios": "Templários",
    "Termmetro": "Termômetro",
    "Toddy Light em p": "Toddy Light em pó",
    "Trip para celular": "Tripé para celular",
    "Troca de leo etc.": "Troca de óleo etc.",
    "Variao cambial": "Variação cambial",
    "Vitamina de Aa": "Vitamina de Açaí",
    "Xcara": "Xícara",
  },
  group: {
    "lcool": "Álcool",
    "Bnus": "Bônus",
    "Cobrana Indevida": "Cobrança Indevida",
    "Contribuio": "Contribuição",
    "Doao": "Doação",
    "Eletrodomstico": "Eletrodoméstico",
    "Estimao": "Estimação",
    "Farmcia": "Farmácia",
    "Ita": "Itaú",
    "Miscelnea": "Miscelânea",
    "Moblia": "Mobília",
    "Operao": "Operação",
    "Prmio": "Prêmio",
    "Sade": "Saúde",
    "Salrio": "Salário",
    "Servios": "Serviços",
    "Tecido Areo": "Tecido Aéreo",
    "Vesturio e acessrios": "Vestuário e acessórios",
  },
};
